
package org.qualipso.factory.client.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "SecurityServiceException", targetNamespace = "http://org.qualipso.factory.ws/service/security")
public class SecurityServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SecurityServiceException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public SecurityServiceException_Exception(String message, SecurityServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public SecurityServiceException_Exception(String message, SecurityServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.qualipso.factory.client.ws.SecurityServiceException
     */
    public SecurityServiceException getFaultInfo() {
        return faultInfo;
    }

}
