
package org.qualipso.factory.client.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ProjectServiceException", targetNamespace = "http://org.qualipso.factory.ws/service/project")
public class ProjectServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ProjectServiceException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ProjectServiceException_Exception(String message, ProjectServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ProjectServiceException_Exception(String message, ProjectServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.qualipso.factory.client.ws.ProjectServiceException
     */
    public ProjectServiceException getFaultInfo() {
        return faultInfo;
    }

}
