
package org.qualipso.factory.client.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "svn", targetNamespace = "http://org.qualipso.factory.ws/service/svn")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Svn {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SVNServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "identifiant", partName = "identifiant")
    public String createSVNRepository(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2)
        throws SVNServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws SVNServiceException_Exception
     */
    @WebMethod
    public void deleteSVNRepository(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws SVNServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns org.qualipso.factory.client.ws.FactoryResource
     * @throws InvalidPathException_Exception
     * @throws AccessDeniedException_Exception
     * @throws FactoryException_Exception
     * @throws PathNotFoundException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public FactoryResource findResource(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws AccessDeniedException_Exception, FactoryException_Exception, InvalidPathException_Exception, PathNotFoundException_Exception
    ;

    /**
     * 
     * @return
     *     returns org.qualipso.factory.client.ws.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public StringArray getResourceTypeList();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getServiceName();

    /**
     * 
     * @param arg0
     * @return
     *     returns org.qualipso.factory.client.ws.SvnRepository
     * @throws SVNServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "svn-repository", partName = "svn-repository")
    public SvnRepository readSVNRepository(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws SVNServiceException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws SVNServiceException_Exception
     */
    @WebMethod
    public void updateSVNRepository(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2)
        throws SVNServiceException_Exception
    ;

}
