
package org.qualipso.factory.client.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "workflow", targetNamespace = "http://org.qualipso.factory.ws/service/workflow")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Workflow {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void deleteInstance(
        @WebParam(name = "arg0", partName = "arg0")
        Bonita arg0);

    /**
     * 
     */
    @WebMethod
    public void deployProjectWorkflow();

    /**
     * 
     * @param arg0
     * @return
     *     returns org.qualipso.factory.client.ws.FactoryResource
     * @throws PathNotFoundException_Exception
     * @throws FactoryException_Exception
     * @throws InvalidPathException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public FactoryResource findResource(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws AccessDeniedException_Exception, FactoryException_Exception, InvalidPathException_Exception, PathNotFoundException_Exception
    ;

    /**
     * 
     * @return
     *     returns org.qualipso.factory.client.ws.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public StringArray getResourceTypeList();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getServiceName();

    /**
     * 
     * @param arg0
     * @return
     *     returns org.qualipso.factory.client.ws.BonitaArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public BonitaArray getTasksReadyForProfile(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getUserConnected();

    /**
     * 
     * @return
     *     returns org.qualipso.factory.client.ws.ProcessInstanceUUID
     */
    @WebMethod
    @WebResult(partName = "return")
    public ProcessInstanceUUID instantiateProjectWorkflow();

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    public void performTaskCreateProject(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        Bonita arg4);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    public void performTaskValidateProject(
        @WebParam(name = "arg0", partName = "arg0")
        boolean arg0,
        @WebParam(name = "arg1", partName = "arg1")
        Bonita arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void resumeTask(
        @WebParam(name = "arg0", partName = "arg0")
        Bonita arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void suspendTask(
        @WebParam(name = "arg0", partName = "arg0")
        Bonita arg0);

    /**
     * 
     */
    @WebMethod
    public void unDeployProjectWorkflow();

}
