
package org.qualipso.factory.svn.client.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "PropertyNotFoundException", targetNamespace = "http://org.qualipso.factory.ws/service/membership")
public class PropertyNotFoundException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PropertyNotFoundException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public PropertyNotFoundException_Exception(String message, PropertyNotFoundException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public PropertyNotFoundException_Exception(String message, PropertyNotFoundException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.qualipso.factory.svn.client.ws.PropertyNotFoundException
     */
    public PropertyNotFoundException getFaultInfo() {
        return faultInfo;
    }

}
