
package org.qualipso.factory.svn.client.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "svn", targetNamespace = "http://org.qualipso.factory.ws/service/svn", wsdlLocation = "http://localhost:8080/factory-svn/svn?wsdl")
public class Svn_Service
    extends Service
{

    private final static URL SVN_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.qualipso.factory.svn.client.ws.Svn_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.qualipso.factory.svn.client.ws.Svn_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/factory-svn/svn?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/factory-svn/svn?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SVN_WSDL_LOCATION = url;
    }

    public Svn_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Svn_Service() {
        super(SVN_WSDL_LOCATION, new QName("http://org.qualipso.factory.ws/service/svn", "svn"));
    }

    /**
     * 
     * @return
     *     returns Svn
     */
    @WebEndpoint(name = "SVNServiceBeanPort")
    public Svn getSVNServiceBeanPort() {
        return super.getPort(new QName("http://org.qualipso.factory.ws/service/svn", "SVNServiceBeanPort"), Svn.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Svn
     */
    @WebEndpoint(name = "SVNServiceBeanPort")
    public Svn getSVNServiceBeanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://org.qualipso.factory.ws/service/svn", "SVNServiceBeanPort"), Svn.class, features);
    }

}
