
package org.factory.qualipso.service.skillmanagement.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "skill", targetNamespace = "http://org.qualipso.factory.ws/service/skill")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Skill {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "int", partName = "int")
    public int controlAddTopicCompetence(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "int", partName = "int")
    public int controlAdmin(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "int", partName = "int")
    public int controlNameCompetence(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "int", partName = "int")
    public int controlNameTopic(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "int", partName = "int")
    public int controlNameTypology(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "int", partName = "int")
    public int controlSkill(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "int", partName = "int")
    public int controlTopEnable(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "int", partName = "int")
    public int controlUserTop(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "int", partName = "int")
    public int controlUserTyp(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    public void deleteCompWithTopic(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    public void deleteMySkill(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    public void deleteTop(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    public void deleteTopComp(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    public void deleteTyp(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    public void disableTop(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    public void disableTyp(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    public void enableAll(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    public void enableTop(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    public void enableTyp(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns org.factory.qualipso.service.skillmanagement.wsclient.FactoryResource
     * @throws FactoryException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public FactoryResource findResource(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws FactoryException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "String", partName = "String")
    public String getProfilesPath()
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns org.factory.qualipso.service.skillmanagement.wsclient.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public StringArray getResourceTypeList();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getServiceName();

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    public void insertComp(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    public void insertCompTop(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    public void insertMySkill(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    public void insertTop(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    public void insertTyp(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns org.factory.qualipso.service.skillmanagement.wsclient.ArrayOfSupportSQLUser
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ArrayOfSupportSQLUser", partName = "ArrayOfSupportSQLUser")
    public ArrayOfSupportSQLUser searchAllUser(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns org.factory.qualipso.service.skillmanagement.wsclient.ArrayOfSupportSQLUserComp
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ArrayOfSupportSQLUserComp", partName = "ArrayOfSupportSQLUserComp")
    public ArrayOfSupportSQLUserComp searchCompUser(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns org.factory.qualipso.service.skillmanagement.wsclient.ArrayOfSupportSQLGapTopic
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ArrayOfSupportSQLGapTopic", partName = "ArrayOfSupportSQLGapTopic")
    public ArrayOfSupportSQLGapTopic searchGapTopic(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns org.factory.qualipso.service.skillmanagement.wsclient.ArrayOfSupportSQLUser
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ArrayOfSupportSQLUser", partName = "ArrayOfSupportSQLUser")
    public ArrayOfSupportSQLUser searchTopUser(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns org.factory.qualipso.service.skillmanagement.wsclient.ArrayOfSupportSQLUser
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ArrayOfSupportSQLUser", partName = "ArrayOfSupportSQLUser")
    public ArrayOfSupportSQLUser searchTypUser(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns org.factory.qualipso.service.skillmanagement.wsclient.ArrayOfSupportSQLComp
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ArrayOfSupportSQLComp", partName = "ArrayOfSupportSQLComp")
    public ArrayOfSupportSQLComp selectComp()
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns org.factory.qualipso.service.skillmanagement.wsclient.ArrayOfSupportSQLLev
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ArrayOfSupportSQLLev", partName = "ArrayOfSupportSQLLev")
    public ArrayOfSupportSQLLev selectLev()
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns org.factory.qualipso.service.skillmanagement.wsclient.ArrayOfSupportSQLUser
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ArrayOfSupportSQLUser", partName = "ArrayOfSupportSQLUser")
    public ArrayOfSupportSQLUser selectMyUser(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns org.factory.qualipso.service.skillmanagement.wsclient.ArrayOfSupportSQLTop
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ArrayOfSupportSQLTop", partName = "ArrayOfSupportSQLTop")
    public ArrayOfSupportSQLTop selectTop()
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns org.factory.qualipso.service.skillmanagement.wsclient.ArrayOfSupportSQLCompTop
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ArrayOfSupportSQLCompTop", partName = "ArrayOfSupportSQLCompTop")
    public ArrayOfSupportSQLCompTop selectTopComp(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns org.factory.qualipso.service.skillmanagement.wsclient.ArrayOfSupportSQLTop
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ArrayOfSupportSQLTop", partName = "ArrayOfSupportSQLTop")
    public ArrayOfSupportSQLTop selectTopSkill()
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns org.factory.qualipso.service.skillmanagement.wsclient.ArrayOfSupportSQL
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ArrayOfSupportSQL", partName = "ArrayOfSupportSQL")
    public ArrayOfSupportSQL selectTyp()
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns org.factory.qualipso.service.skillmanagement.wsclient.ArrayOfSupportSQL
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "ArrayOfSupportSQL", partName = "ArrayOfSupportSQL")
    public ArrayOfSupportSQL selectTypTrue()
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    public void updateTop(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2)
        throws SkillServiceException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws SkillServiceException_Exception
     */
    @WebMethod
    public void updateTyp(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2)
        throws SkillServiceException_Exception
    ;

}
