
package org.qualipso.factory.bugtracker.client.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "BugTrackerServiceException", targetNamespace = "http://org.qualipso.factory.ws/service/bugtracker")
public class BugTrackerServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BugTrackerServiceException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public BugTrackerServiceException_Exception(String message, BugTrackerServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public BugTrackerServiceException_Exception(String message, BugTrackerServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.qualipso.factory.bugtracker.client.ws.BugTrackerServiceException
     */
    public BugTrackerServiceException getFaultInfo() {
        return faultInfo;
    }

}
