
package ws.factory.qualipso.org.service.bootstrap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import net.java.dev.jaxb.array.StringArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BootstrapService", targetNamespace = "http://org.qualipso.factory.ws/service/bootstrap")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    net.java.dev.jaxb.array.ObjectFactory.class,
    ws.factory.qualipso.org.service.bootstrap.ObjectFactory.class,
    ws.factory.qualipso.org.resource.file.ObjectFactory.class,
    ws.factory.qualipso.org.resource.link.ObjectFactory.class,
    ws.factory.qualipso.org.resource.profile.ObjectFactory.class,
    ws.factory.qualipso.org.resource.folder.ObjectFactory.class,
    ws.factory.qualipso.org.resource.group.ObjectFactory.class
})
public interface BootstrapService {


    /**
     * 
     * @throws BootstrapServiceException_Exception
     */
    @WebMethod
    public void bootstrap()
        throws BootstrapServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns ws.factory.qualipso.org.service.bootstrap.FactoryResource
     * @throws FactoryException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public FactoryResource findResource(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws FactoryException_Exception
    ;

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public StringArray getResourceTypeList();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getServiceName();

}
