
package org.qualipso.factory.helloworld.client.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloWorldService", targetNamespace = "http://org.qualipso.factory.ws/service/helloworld", wsdlLocation = "http://localhost:8080/factory-service-helloworld/helloworld?wsdl")
public class HelloWorldService_Service
    extends Service
{

    private final static URL HELLOWORLDSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.qualipso.factory.helloworld.client.ws.HelloWorldService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.qualipso.factory.helloworld.client.ws.HelloWorldService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/factory-service-helloworld/helloworld?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/factory-service-helloworld/helloworld?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HELLOWORLDSERVICE_WSDL_LOCATION = url;
    }

    public HelloWorldService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldService_Service() {
        super(HELLOWORLDSERVICE_WSDL_LOCATION, new QName("http://org.qualipso.factory.ws/service/helloworld", "HelloWorldService"));
    }

    /**
     * 
     * @return
     *     returns HelloWorldService
     */
    @WebEndpoint(name = "HelloWorldServicePort")
    public HelloWorldService getHelloWorldServicePort() {
        return super.getPort(new QName("http://org.qualipso.factory.ws/service/helloworld", "HelloWorldServicePort"), HelloWorldService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldService
     */
    @WebEndpoint(name = "HelloWorldServicePort")
    public HelloWorldService getHelloWorldServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://org.qualipso.factory.ws/service/helloworld", "HelloWorldServicePort"), HelloWorldService.class, features);
    }

}
