
package org.qualipso.factory.helloworld.client.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "HelloWorldServiceException", targetNamespace = "http://org.qualipso.factory.ws/service/helloworld")
public class HelloWorldServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private HelloWorldServiceException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public HelloWorldServiceException_Exception(String message, HelloWorldServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public HelloWorldServiceException_Exception(String message, HelloWorldServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.qualipso.factory.helloworld.client.ws.HelloWorldServiceException
     */
    public HelloWorldServiceException getFaultInfo() {
        return faultInfo;
    }

}
