
package org.qualipso.factory.git.client.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "BootstrapServiceException", targetNamespace = "http://org.qualipso.factory.ws/service/bootstrap")
public class BootstrapServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BootstrapServiceException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public BootstrapServiceException_Exception(String message, BootstrapServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public BootstrapServiceException_Exception(String message, BootstrapServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.qualipso.factory.git.client.ws.BootstrapServiceException
     */
    public BootstrapServiceException getFaultInfo() {
        return faultInfo;
    }

}
