
package org.qualipso.factory.git.client.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "GITServiceException", targetNamespace = "http://org.qualipso.factory.ws/service/git")
public class GITServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GITServiceException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public GITServiceException_Exception(String message, GITServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public GITServiceException_Exception(String message, GITServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.qualipso.factory.git.client.ws.GITServiceException
     */
    public GITServiceException getFaultInfo() {
        return faultInfo;
    }

}
