
package org.qualipso.factory.git.client.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "PathNotEmptyException", targetNamespace = "http://org.qualipso.factory.ws/service/git")
public class PathNotEmptyException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PathNotEmptyException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public PathNotEmptyException_Exception(String message, PathNotEmptyException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public PathNotEmptyException_Exception(String message, PathNotEmptyException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.qualipso.factory.git.client.ws.PathNotEmptyException
     */
    public PathNotEmptyException getFaultInfo() {
        return faultInfo;
    }

}
