
package org.factory.qualipso.service.skillmanagement.wsclient.ws.factory.qualipso.org.service.skill;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "SkillServiceException", targetNamespace = "http://org.qualipso.factory.ws/service/skill")
public class SkillServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SkillServiceException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public SkillServiceException_Exception(String message, SkillServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public SkillServiceException_Exception(String message, SkillServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ws.factory.qualipso.org.service.skill.SkillServiceException
     */
    public SkillServiceException getFaultInfo() {
        return faultInfo;
    }

}
