
package org.qualipso.factory.collaboration.client.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "calendar", targetNamespace = "http://org.qualipso.factory.ws/service/calendar")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calendar {


    /**
     * 
     * @param profilePath
     * @param path
     * @throws CalendarServiceException_Exception
     */
    @WebMethod
    public void addEventParticipants(
        @WebParam(name = "path", partName = "path")
        String path,
        @WebParam(name = "profile-path", partName = "profile-path")
        StringArray profilePath)
        throws CalendarServiceException_Exception
    ;

    /**
     * 
     * @param forumPath
     * @param path
     * @throws CalendarServiceException_Exception
     */
    @WebMethod
    public void attachForumToEvent(
        @WebParam(name = "path", partName = "path")
        String path,
        @WebParam(name = "forumPath", partName = "forumPath")
        String forumPath)
        throws CalendarServiceException_Exception
    ;

    /**
     * 
     * @param documentPath
     * @param path
     * @throws CalendarServiceException_Exception
     */
    @WebMethod
    public void atttachDocumentToEvent(
        @WebParam(name = "path", partName = "path")
        String path,
        @WebParam(name = "documentPath", partName = "documentPath")
        StringArray documentPath)
        throws CalendarServiceException_Exception
    ;

    /**
     * 
     * @param calendarDetails
     * @param parentPath
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.StringArray
     * @throws CalendarServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "paths", partName = "paths")
    public StringArray createEvent(
        @WebParam(name = "parent-path", partName = "parent-path")
        String parentPath,
        @WebParam(name = "calendar-details", partName = "calendar-details")
        CalendarDetails calendarDetails)
        throws CalendarServiceException_Exception
    ;

    /**
     * 
     * @param forumPath
     * @param calendarDetails
     * @param attachments
     * @param parentPath
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.StringArray
     * @throws CalendarServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "paths", partName = "paths")
    public StringArray createEventWithAttachments(
        @WebParam(name = "parent-path", partName = "parent-path")
        String parentPath,
        @WebParam(name = "calendar-details", partName = "calendar-details")
        CalendarDetails calendarDetails,
        @WebParam(name = "attachments", partName = "attachments")
        StringArray attachments,
        @WebParam(name = "forumPath", partName = "forumPath")
        String forumPath)
        throws CalendarServiceException_Exception
    ;

    /**
     * 
     * @param path
     * @throws CalendarServiceException_Exception
     */
    @WebMethod
    public void deleteEvent(
        @WebParam(name = "path", partName = "path")
        String path)
        throws CalendarServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.FactoryResource
     * @throws FactoryException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public FactoryResource findResource(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws FactoryException_Exception
    ;

    /**
     * 
     * @param path
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.CalendarItemArray
     * @throws CalendarServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "calendar-items", partName = "calendar-items")
    public CalendarItemArray getCalendarItems(
        @WebParam(name = "path", partName = "path")
        String path)
        throws CalendarServiceException_Exception
    ;

    /**
     * 
     * @param month
     * @param path
     * @param year
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.CalendarItemArray
     * @throws CalendarServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "calendar-items", partName = "calendar-items")
    public CalendarItemArray getCalendarItemsForMonth(
        @WebParam(name = "path", partName = "path")
        String path,
        @WebParam(name = "year", partName = "year")
        String year,
        @WebParam(name = "month", partName = "month")
        String month)
        throws CalendarServiceException_Exception
    ;

    /**
     * 
     * @param path
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.ParticipantsArray
     * @throws CalendarServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "participants", partName = "participants")
    public ParticipantsArray getEventParticipants(
        @WebParam(name = "path", partName = "path")
        String path)
        throws CalendarServiceException_Exception
    ;

    /**
     * 
     * @param month
     * @param path
     * @param year
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.ListItemArray
     * @throws CalendarServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "calendar-items", partName = "calendar-items")
    public ListItemArray getMonthlyCalendar(
        @WebParam(name = "path", partName = "path")
        String path,
        @WebParam(name = "year", partName = "year")
        String year,
        @WebParam(name = "month", partName = "month")
        String month)
        throws CalendarServiceException_Exception
    ;

    /**
     * 
     * @param month
     * @param year
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.ListItemArray
     * @throws CalendarServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "calendar-items", partName = "calendar-items")
    public ListItemArray getMonthlyCalendarForUser(
        @WebParam(name = "year", partName = "year")
        String year,
        @WebParam(name = "month", partName = "month")
        String month)
        throws CalendarServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public StringArray getResourceTypeList();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getServiceName();

    /**
     * 
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.StringArray
     * @throws CalendarServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "events", partName = "events")
    public StringArray getUserParticipations()
        throws CalendarServiceException_Exception
    ;

    /**
     * 
     * @param path
     * @param decision
     * @throws CalendarServiceException_Exception
     */
    @WebMethod
    public void handleInvitation(
        @WebParam(name = "path", partName = "path")
        String path,
        @WebParam(name = "decision", partName = "decision")
        String decision)
        throws CalendarServiceException_Exception
    ;

    /**
     * 
     * @param path
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.CalendarItem
     * @throws CalendarServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "calendar-item", partName = "calendar-item")
    public CalendarItem readEvent(
        @WebParam(name = "path", partName = "path")
        String path)
        throws CalendarServiceException_Exception
    ;

    /**
     * 
     * @param path
     * @param calendarDetails
     * @return
     *     returns java.lang.String
     * @throws CalendarServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "updated-path", partName = "updated-path")
    public String updateEvent(
        @WebParam(name = "path", partName = "path")
        String path,
        @WebParam(name = "calendar-details", partName = "calendar-details")
        CalendarEvent calendarDetails)
        throws CalendarServiceException_Exception
    ;

    /**
     * 
     * @param forumPath
     * @param path
     * @param calendarDetails
     * @param profiles
     * @param attachments
     * @param groups
     * @throws CalendarServiceException_Exception
     */
    @WebMethod
    public void updateEventAdvanced(
        @WebParam(name = "path", mode = WebParam.Mode.INOUT, partName = "path")
        Holder<String> path,
        @WebParam(name = "calendar-details", partName = "calendar-details")
        CalendarEvent calendarDetails,
        @WebParam(name = "attachments", partName = "attachments")
        StringArray attachments,
        @WebParam(name = "forumPath", partName = "forumPath")
        String forumPath,
        @WebParam(name = "profiles", partName = "profiles")
        StringArray profiles,
        @WebParam(name = "groups", partName = "groups")
        StringArray groups)
        throws CalendarServiceException_Exception
    ;

    /**
     * 
     * @param extraDetails
     * @param path
     * @param calendarDetails
     * @return
     *     returns java.lang.String
     * @throws CalendarServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "updated-path", partName = "updated-path")
    public String updateEventExtra(
        @WebParam(name = "path", partName = "path")
        String path,
        @WebParam(name = "calendar-details", partName = "calendar-details")
        CalendarEvent calendarDetails,
        @WebParam(name = "extra-details", partName = "extra-details")
        ExtraDetails extraDetails)
        throws CalendarServiceException_Exception
    ;

    /**
     * 
     * @param forumPath
     * @param path
     * @param calendarDetails
     * @param attachments
     * @return
     *     returns java.lang.String
     * @throws CalendarServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "updated-path", partName = "updated-path")
    public String updateEventWithAttachments(
        @WebParam(name = "path", partName = "path")
        String path,
        @WebParam(name = "calendar-details", partName = "calendar-details")
        CalendarEvent calendarDetails,
        @WebParam(name = "attachments", partName = "attachments")
        StringArray attachments,
        @WebParam(name = "forumPath", partName = "forumPath")
        String forumPath)
        throws CalendarServiceException_Exception
    ;

    /**
     * 
     * @param recurrence
     * @param times
     * @param path
     * @param date
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.StringArray
     * @throws CalendarServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "paths", partName = "paths")
    public StringArray updateRecurrence(
        @WebParam(name = "path", partName = "path")
        String path,
        @WebParam(name = "date", partName = "date")
        String date,
        @WebParam(name = "recurrence", partName = "recurrence")
        String recurrence,
        @WebParam(name = "times", partName = "times")
        long times)
        throws CalendarServiceException_Exception
    ;

}
