
package org.qualipso.factory.collaboration.client.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "core", targetNamespace = "http://org.qualipso.factory.ws/service/core")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Core {


    /**
     * 
     * @param description
     * @param path
     * @param filename
     * @param contentType
     * @param fileData
     * @throws CoreServiceException_Exception
     */
    @WebMethod
    public void createFile(
        @WebParam(name = "path", partName = "path")
        String path,
        @WebParam(name = "filename", partName = "filename")
        String filename,
        @WebParam(name = "content-type", partName = "content-type")
        String contentType,
        @WebParam(name = "description", partName = "description")
        String description,
        @WebParam(name = "file-data", partName = "file-data")
        FileData fileData)
        throws CoreServiceException_Exception
    ;

    /**
     * 
     * @param description
     * @param name
     * @param path
     * @throws CoreServiceException_Exception
     */
    @WebMethod
    public void createFolder(
        @WebParam(name = "path", partName = "path")
        String path,
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "description", partName = "description")
        String description)
        throws CoreServiceException_Exception
    ;

    /**
     * 
     * @param toPath
     * @param path
     * @throws CoreServiceException_Exception
     */
    @WebMethod
    public void createLink(
        @WebParam(name = "path", partName = "path")
        String path,
        @WebParam(name = "to-path", partName = "to-path")
        String toPath)
        throws CoreServiceException_Exception
    ;

    /**
     * 
     * @param path
     * @throws CoreServiceException_Exception
     */
    @WebMethod
    public void deleteFile(
        @WebParam(name = "path", partName = "path")
        String path)
        throws CoreServiceException_Exception
    ;

    /**
     * 
     * @param path
     * @throws CoreServiceException_Exception
     */
    @WebMethod
    public void deleteFolder(
        @WebParam(name = "path", partName = "path")
        String path)
        throws CoreServiceException_Exception
    ;

    /**
     * 
     * @param path
     * @throws CoreServiceException_Exception
     */
    @WebMethod
    public void deleteLink(
        @WebParam(name = "path", partName = "path")
        String path)
        throws CoreServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.FactoryResource
     * @throws FactoryException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public FactoryResource findResource(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws FactoryException_Exception
    ;

    /**
     * 
     * @param path
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.FileData
     * @throws CoreServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "file-data", partName = "file-data")
    public FileData getFileData(
        @WebParam(name = "path", partName = "path")
        String path)
        throws CoreServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public StringArray getResourceTypeList();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getServiceName();

    /**
     * 
     * @param path
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.File
     * @throws CoreServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "file", partName = "file")
    public File readFile(
        @WebParam(name = "path", partName = "path")
        String path)
        throws CoreServiceException_Exception
    ;

    /**
     * 
     * @param path
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.Folder
     * @throws CoreServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "folder", partName = "folder")
    public Folder readFolder(
        @WebParam(name = "path", partName = "path")
        String path)
        throws CoreServiceException_Exception
    ;

    /**
     * 
     * @param path
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.Link
     * @throws CoreServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "link", partName = "link")
    public Link readLink(
        @WebParam(name = "path", partName = "path")
        String path)
        throws CoreServiceException_Exception
    ;

    /**
     * 
     * @param description
     * @param path
     * @param filename
     * @param contentType
     * @param fileData
     * @throws CoreServiceException_Exception
     */
    @WebMethod
    public void updateFile(
        @WebParam(name = "path", partName = "path")
        String path,
        @WebParam(name = "filename", partName = "filename")
        String filename,
        @WebParam(name = "content-type", partName = "content-type")
        String contentType,
        @WebParam(name = "description", partName = "description")
        String description,
        @WebParam(name = "file-data", partName = "file-data")
        FileData fileData)
        throws CoreServiceException_Exception
    ;

    /**
     * 
     * @param description
     * @param name
     * @param path
     * @throws CoreServiceException_Exception
     */
    @WebMethod
    public void updateFolder(
        @WebParam(name = "path", partName = "path")
        String path,
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "description", partName = "description")
        String description)
        throws CoreServiceException_Exception
    ;

    /**
     * 
     * @param toPath
     * @param path
     * @throws CoreServiceException_Exception
     */
    @WebMethod
    public void updateLink(
        @WebParam(name = "path", partName = "path")
        String path,
        @WebParam(name = "to-path", partName = "to-path")
        String toPath)
        throws CoreServiceException_Exception
    ;

}
