
package org.qualipso.factory.collaboration.client.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "forum-management", targetNamespace = "http://org.qualipso.factory.ws/service/forum-management", wsdlLocation = "http://localhost:8380/factory-service-collaboration/forum-management?wsdl")
public class ForumManagement_Service
    extends Service
{

    private final static URL FORUMMANAGEMENT_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.qualipso.factory.collaboration.client.ws.ForumManagement_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.qualipso.factory.collaboration.client.ws.ForumManagement_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8380/factory-service-collaboration/forum-management?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8380/factory-service-collaboration/forum-management?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FORUMMANAGEMENT_WSDL_LOCATION = url;
    }

    public ForumManagement_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ForumManagement_Service() {
        super(FORUMMANAGEMENT_WSDL_LOCATION, new QName("http://org.qualipso.factory.ws/service/forum-management", "forum-management"));
    }

    /**
     * 
     * @return
     *     returns ForumManagement
     */
    @WebEndpoint(name = "forum-managementPort")
    public ForumManagement getForumManagementPort() {
        return super.getPort(new QName("http://org.qualipso.factory.ws/service/forum-management", "forum-managementPort"), ForumManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ForumManagement
     */
    @WebEndpoint(name = "forum-managementPort")
    public ForumManagement getForumManagementPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://org.qualipso.factory.ws/service/forum-management", "forum-managementPort"), ForumManagement.class, features);
    }

}
