
package org.qualipso.factory.collaboration.client.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "forum-management", targetNamespace = "http://org.qualipso.factory.ws/service/forum-management")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ForumManagement {


    /**
     * 
     * @param path
     * @param attachments
     * @throws ForumServiceException_Exception
     */
    @WebMethod
    public void attachDocumentsToForum(
        @WebParam(name = "path", partName = "path")
        String path,
        @WebParam(name = "attachments", partName = "attachments")
        StringArray attachments)
        throws ForumServiceException_Exception
    ;

    /**
     * 
     * @param path
     * @throws ForumServiceException_Exception
     */
    @WebMethod
    public void changeForumStatus(
        @WebParam(name = "path", partName = "path")
        String path)
        throws ForumServiceException_Exception
    ;

    /**
     * 
     * @param name
     * @param parentPath
     * @return
     *     returns java.lang.String
     * @throws ForumServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "path", partName = "path")
    public String createForum(
        @WebParam(name = "parent-path", partName = "parent-path")
        String parentPath,
        @WebParam(name = "name", partName = "name")
        String name)
        throws ForumServiceException_Exception
    ;

    /**
     * 
     * @param threadMessage
     * @param parentPath
     * @return
     *     returns java.lang.String
     * @throws ForumServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "path", partName = "path")
    public String createThreadMessage(
        @WebParam(name = "parent-path", partName = "parent-path")
        String parentPath,
        @WebParam(name = "thread-message", partName = "thread-message")
        ThreadDetails threadMessage)
        throws ForumServiceException_Exception
    ;

    /**
     * 
     * @param threadMessage
     * @param attachments
     * @param parentPath
     * @return
     *     returns java.lang.String
     * @throws ForumServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "path", partName = "path")
    public String createThreadMessageWithAttachments(
        @WebParam(name = "parent-path", partName = "parent-path")
        String parentPath,
        @WebParam(name = "thread-message", partName = "thread-message")
        ThreadDetails threadMessage,
        @WebParam(name = "attachments", partName = "attachments")
        StringArray attachments)
        throws ForumServiceException_Exception
    ;

    /**
     * 
     * @param path
     * @throws ForumServiceException_Exception
     */
    @WebMethod
    public void deleteForum(
        @WebParam(name = "path", partName = "path")
        String path)
        throws ForumServiceException_Exception
    ;

    /**
     * 
     * @param path
     * @throws ForumServiceException_Exception
     */
    @WebMethod
    public void deleteThreadMessage(
        @WebParam(name = "path", partName = "path")
        String path)
        throws ForumServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.FactoryResource
     * @throws FactoryException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public FactoryResource findResource(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws FactoryException_Exception
    ;

    /**
     * 
     * @param path
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.ThreadMessageArray
     * @throws ForumServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "thread-messages", partName = "thread-messages")
    public ThreadMessageArray getForumMessages(
        @WebParam(name = "path", partName = "path")
        String path)
        throws ForumServiceException_Exception
    ;

    /**
     * 
     * @param path
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.ForumArray
     * @throws ForumServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "forums", partName = "forums")
    public ForumArray getForums(
        @WebParam(name = "path", partName = "path")
        String path)
        throws ForumServiceException_Exception
    ;

    /**
     * 
     * @param status
     * @param path
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.ForumArray
     * @throws ForumServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "forums", partName = "forums")
    public ForumArray getForumsByStatus(
        @WebParam(name = "path", partName = "path")
        String path,
        @WebParam(name = "status", partName = "status")
        String status)
        throws ForumServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public StringArray getResourceTypeList();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getServiceName();

    /**
     * 
     * @param path
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.ThreadMessageArray
     * @throws ForumServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "thread-messages", partName = "thread-messages")
    public ThreadMessageArray getThreadReplies(
        @WebParam(name = "path", partName = "path")
        String path)
        throws ForumServiceException_Exception
    ;

    /**
     * 
     * @param path
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.Forum
     * @throws ForumServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "forum", partName = "forum")
    public Forum readForum(
        @WebParam(name = "path", partName = "path")
        String path)
        throws ForumServiceException_Exception
    ;

    /**
     * 
     * @param path
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.Forum
     * @throws ForumServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "forum", partName = "forum")
    public Forum readForumProperties(
        @WebParam(name = "path", partName = "path")
        String path)
        throws ForumServiceException_Exception
    ;

    /**
     * 
     * @param path
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.ThreadMessage
     * @throws ForumServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "thread-message", partName = "thread-message")
    public ThreadMessage readThreadMessage(
        @WebParam(name = "path", partName = "path")
        String path)
        throws ForumServiceException_Exception
    ;

    /**
     * 
     * @param path
     * @return
     *     returns org.qualipso.factory.collaboration.client.ws.ThreadMessage
     * @throws ForumServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "thread-message", partName = "thread-message")
    public ThreadMessage readThreadMessageProperties(
        @WebParam(name = "path", partName = "path")
        String path)
        throws ForumServiceException_Exception
    ;

    /**
     * 
     * @param name
     * @param path
     * @param date
     * @throws ForumServiceException_Exception
     */
    @WebMethod
    public void updateForum(
        @WebParam(name = "path", partName = "path")
        String path,
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "date", partName = "date")
        String date)
        throws ForumServiceException_Exception
    ;

    /**
     * 
     * @param name
     * @param path
     * @param attachments
     * @param date
     * @throws ForumServiceException_Exception
     */
    @WebMethod
    public void updateForumWithAttachments(
        @WebParam(name = "path", partName = "path")
        String path,
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "date", partName = "date")
        String date,
        @WebParam(name = "attachments", partName = "attachments")
        StringArray attachments)
        throws ForumServiceException_Exception
    ;

}
