
package org.qualipso.factory.greeting.client.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "greeting", targetNamespace = "http://org.qualipso.factory.ws/service/greeting", wsdlLocation = "http://localhost:8080/factory-greeting/greeting?wsdl")
public class Greeting_Service
    extends Service
{

    private final static URL GREETING_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.qualipso.factory.greeting.client.ws.Greeting_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.qualipso.factory.greeting.client.ws.Greeting_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/factory-greeting/greeting?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/factory-greeting/greeting?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GREETING_WSDL_LOCATION = url;
    }

    public Greeting_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Greeting_Service() {
        super(GREETING_WSDL_LOCATION, new QName("http://org.qualipso.factory.ws/service/greeting", "greeting"));
    }

    /**
     * 
     * @return
     *     returns Greeting
     */
    @WebEndpoint(name = "GreetingServiceBeanPort")
    public Greeting getGreetingServiceBeanPort() {
        return super.getPort(new QName("http://org.qualipso.factory.ws/service/greeting", "GreetingServiceBeanPort"), Greeting.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Greeting
     */
    @WebEndpoint(name = "GreetingServiceBeanPort")
    public Greeting getGreetingServiceBeanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://org.qualipso.factory.ws/service/greeting", "GreetingServiceBeanPort"), Greeting.class, features);
    }

}
