
package org.qualipso.factory.greeting.client.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "GreetingServiceException", targetNamespace = "http://org.qualipso.factory.ws/service/greeting")
public class GreetingServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GreetingServiceException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public GreetingServiceException_Exception(String message, GreetingServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public GreetingServiceException_Exception(String message, GreetingServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.qualipso.factory.greeting.client.ws.GreetingServiceException
     */
    public GreetingServiceException getFaultInfo() {
        return faultInfo;
    }

}
