
package org.qualipso.factory.client.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "SVNServiceException", targetNamespace = "http://org.qualipso.factory.ws/service/svn")
public class SVNServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SVNServiceException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public SVNServiceException_Exception(String message, SVNServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public SVNServiceException_Exception(String message, SVNServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.qualipso.factory.client.ws.SVNServiceException
     */
    public SVNServiceException getFaultInfo() {
        return faultInfo;
    }

}
