
package org.qualipso.factory.client.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "workflow", targetNamespace = "http://org.qualipso.factory.ws/service/workflow", wsdlLocation = "http://localhost:8280/workflow/workflow?wsdl")
public class Workflow_Service
    extends Service
{

    private final static URL WORKFLOW_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.qualipso.factory.client.ws.Workflow_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.qualipso.factory.client.ws.Workflow_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8280/workflow/workflow?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8280/workflow/workflow?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WORKFLOW_WSDL_LOCATION = url;
    }

    public Workflow_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Workflow_Service() {
        super(WORKFLOW_WSDL_LOCATION, new QName("http://org.qualipso.factory.ws/service/workflow", "workflow"));
    }

    /**
     * 
     * @return
     *     returns Workflow
     */
    @WebEndpoint(name = "BonitaServiceBeanPort")
    public Workflow getBonitaServiceBeanPort() {
        return super.getPort(new QName("http://org.qualipso.factory.ws/service/workflow", "BonitaServiceBeanPort"), Workflow.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Workflow
     */
    @WebEndpoint(name = "BonitaServiceBeanPort")
    public Workflow getBonitaServiceBeanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://org.qualipso.factory.ws/service/workflow", "BonitaServiceBeanPort"), Workflow.class, features);
    }

}
